# 1. The Nginx Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        # Simple health check to ensure Nginx is running
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
---
# 2. The Service (Must be ClusterIP for Ingress)
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
# 3. The Ingress (Exposes the Service via HTTPS)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    # Use the standard GKE Ingress Controller
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - secretName: nginx-tls-secret
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
