apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: advgke-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 
  volumeName: advgke-pv
  storageClassName: ""
